version: '3'

services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=development
    user: node
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - 19006:19006
      - 19001:19001
      - 19002:19002
    volumes:
      - ./ldm-ai:/opt/app:delegated
      #- ./app/package.json:/opt/app/package.json
      #- ./app/package-lock.json:/opt/app/package-lock.json
      - tmp:/opt/app/node_modules:delegated
    healthcheck:
      disable: true

volumes:
  tmp:
